Revert "[wip] adds ansible role support"
This reverts commit 782d88d7282e0c95da36ef606e74b4ea597dfb95.

diff --git a/deployment/scripts/codeship_heroku_deploy b/deployment/scripts/codeship_heroku_deploy
--- a/deployment/scripts/codeship_heroku_deploy
+++ b/deployment/scripts/codeship_heroku_deploy
@@ -1,94 +1,62 @@
 #!/bin/bash
-set -e
-set -o pipefail
 
-PREVIOUS_WORKING_DIRECTORY="${PWD}"
+AFTER_DEPLOYMENT_WAIT_TIME=5
 
-CODESHIP_HEROKU_APP_NAME=${CODESHIP_HEROKU_APP_NAME:-""}
-CODESHIP_HEROKU_API_KEY=${CODESHIP_HEROKU_API_KEY:-""}
-CODESHIP_HEROKU_DEPLOY_FOLDER=${CODESHIP_HEROKU_DEPLOY_FOLDER:-"${PWD}"}
-CODESHIP_HEROKU_POST_DEPLOY_COMMAND=${CODESHIP_HEROKU_POST_DEPLOY_COMMAND:-""}
-CODESHIP_HEROKU_URL=${CODESHIP_HEROKU_URL:-""}
-CODESHIP_HEROKU_CHECK_APP_URL=${CODESHIP_HEROKU_CHECK_APP_URL:-false}
+echo "STARTING DEPLOYMENT"
 
-SCRIPT_DIRECTORY=$(dirname "$0")
+APPLICATION_FOLDER=${1:?'You need to provide the directory with your code as the second parameter'}
+HEROKU_APP_NAME=${2:?'You need to provide the application name as the third parameter'}
 
-function help {
-  cat << EOF
-heroku_deploy Usage:
---
-
-required:
--N or CODESHIP_HEROKU_APP_NAME: heroku app name
--K or CODESHIP_HEROKU_API_KEY: heroku API key
-
-optional:
--f or CODESHIP_HEROKU_DEPLOY_FOLDER: folder to deploy
--d or CODESHIP_HEROKU_POST_DEPLOY_COMMAND: one-off command to run after deployment
--u or CODESHIP_HEROKU_URL: url running the service (to use in conjunction with -c)
--c or CODESHIP_HEROKU_CHECK_APP_URL: check url if service is running after deployment
--h: this
-
-EOF
+function error_message() {
+  echo -e "DEPLOYMENT FAILED on line $1 of the deployment script"
 }
 
+trap 'error_message $LINENO' ERR
 
-while getopts "N:K:f:u:d:ch" opt; do
-  case "$opt" in
-    N)
-      CODESHIP_HEROKU_APP_NAME="$OPTARG"; ;;
-    K)
-      CODESHIP_HEROKU_API_KEY="$OPTARG"; ;;
-    f)
-      CODESHIP_HEROKU_DEPLOY_FOLDER="$OPTARG"; ;;
-    d)
-      CODESHIP_HEROKU_POST_DEPLOY_COMMAND="$OPTARG"; ;;
-    u)
-      CODESHIP_HEROKU_URL="$OPTARG"; ;;
-    c)
-      CODESHIP_HEROKU_CHECK_APP_URL=true; ;;
-    h) help; exit 1 ;;
-    *)
-      help
-      exit 1 ;;
-  esac
-done
+set -o pipefail
+set -e
 
-#input validation
-if [ "${CODESHIP_HEROKU_APP_NAME}" == "" ]; then
-  echo "app-name not set, exiting" >&2
-  help
-  exit 1
-fi
+echo "CHANGING Directory to $APPLICATION_FOLDER"
+cd $APPLICATION_FOLDER
 
-#input validation
-if [ "${CODESHIP_HEROKU_API_KEY}" == "" ]; then
-  echo "api-key not set, exiting" >&2
-  help
-  exit 1
-fi
+echo "CHECKING Access to Heroku application $HEROKU_APP_NAME"
+codeship_heroku check_access $HEROKU_APP_NAME
 
-trap 'echo error executing "$(eval echo "$BASH_COMMAND")" in line $LINENO' ERR
+ARTEFACT_PATH=/tmp/deployable_artifact.tar.gz
 
-if [ "${CODESHIP_HEROKU_DEPLOY_FOLDER}" != "${PWD}" ]; then
-  cd "${CODESHIP_HEROKU_DEPLOY_FOLDER}"
-fi
+echo "PACKAGING Tar.gz for deployment"
+tar -pczf $ARTEFACT_PATH ./
 
-if ! HEROKU_API_KEY=$CODESHIP_HEROKU_API_KEY "${SCRIPT_DIRECTORY}/codeship_heroku_check_access" "${CODESHIP_HEROKU_APP_NAME}"; then
-  echo "could not access heroku app ${CODESHIP_HEROKU_APP_NAME}, exiting" >&2
-  exit 1
-fi
+echo "PREPARING Heroku source for upload"
+sources=`curl -sS -X POST https://api.heroku.com/apps/$HEROKU_APP_NAME/sources -H 'Accept: application/vnd.heroku+json; version=3' -H "Authorization: Bearer $HEROKU_API_KEY"`
 
-#--include-vcs-ignore set for compatibility with Ubuntu 14.04: https://github.com/heroku/heroku-builds/issues/36
-HEROKU_API_KEY=${CODESHIP_HEROKU_API_KEY} heroku builds:create --include-vcs-ignore -a "${CODESHIP_HEROKU_APP_NAME}"
+get_url=`echo $sources | jq -r .source_blob.get_url`
+put_url=`echo $sources | jq -r .source_blob.put_url`
 
-if [ "${CODESHIP_HEROKU_POST_DEPLOY_COMMAND}" != "" ]; then
-  HEROKU_API_KEY=$CODESHIP_HEROKU_API_KEY "${SCRIPT_DIRECTORY}/heroku_run" "${CODESHIP_HEROKU_POST_DEPLOY_COMMAND}" "${CODESHIP_HEROKU_APP_NAME}"
-fi
+echo "UPLOADING Tar.gz file to Heroku"
+curl -sS -X PUT "$put_url" -H 'Content-Type:' --data-binary @$ARTEFACT_PATH
 
-if [ "${CODESHIP_HEROKU_CHECK_APP_URL}" == "true" ]; then
-  URL="${CODESHIP_HEROKU_URL:-"http://${CODESHIP_HEROKU_APP_NAME}.herokuapp.com"}"
-  "${SCRIPT_DIRECTORY}/check_url" "${URL}"
-fi
+echo "STARTING Build process on Heroku"
+deployment=`curl -sS -X POST https://api.heroku.com/apps/$HEROKU_APP_NAME/builds -d "{\"source_blob\":{\"url\":\"$get_url\", \"version\": \"$CI_COMMIT_ID\"}}" -H 'Accept: application/vnd.heroku+json; version=3' -H 'Content-Type: application/json' -H "Authorization: Bearer $HEROKU_API_KEY"`
 
-cd "${PREVIOUS_WORKING_DIRECTORY}"
+deployment_id=`echo "$deployment" | jq -r .id`
+
+echo "DEPLOYMENT: $deployment_id"
+
+output_stream_url=`echo "$deployment" | jq -r .output_stream_url`
+
+curl -sS "$output_stream_url"
+
+# Sleep for 2 seconds to allow Heroku to store the result of the Deployment
+sleep $AFTER_DEPLOYMENT_WAIT_TIME
+
+echo "CHECKING API for deployment success"
+
+deployment_result_json=`curl -sS https://api.heroku.com/apps/$HEROKU_APP_NAME/builds/$deployment_id -H 'Accept: application/vnd.heroku+json; version=3' -H "Authorization: Bearer $HEROKU_API_KEY"`
+
+deployment_status=`echo "$deployment_result_json" | jq -r .status`
+echo "DEPLOYMENT STATUS: $deployment_status"
+
+[ "$deployment_status" = "succeeded" ]
+
+echo "DEPLOYMENT SUCCESSFUL"
